spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: test_password
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: test_password
